// Generates the tiny test assets used by the test suite:
//   tone.wav    - 0.5 s stereo 440 Hz sine, 44.1 kHz
//   2x3.png     - 6x3 RGB color ramp (lossless reference)
//   2x2.jpg     - 2x2 RGB JPEG
//   cube.obj    - classic 8-vertex cube with normals and UVs (24v/36i after load)
//   quad.obj    - two triangles sharing a full vertex tuple (dedupe: 4 verts)
//
// Runs after every build via CMake POST_BUILD; writes into KIMIA_ASSET_DIR
// (default Tests/assets).

#include <kimia/Audio.h>
#include <kimia/Image.h>
#include <kimia/MathUtils.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>

using kimia::f32;
using kimia::f64;
using kimia::i32;
using kimia::u8;
using kimia::u64;
using kimia::usize;

namespace {

std::string assetDir() {
  const char* dir = std::getenv("KIMIA_ASSET_DIR");
  return dir != nullptr ? std::string(dir) : std::string("Tests/assets");
}

bool writeText(const std::string& path, const std::string& content) {
  std::ofstream file(path, std::ios::binary);
  if (!file) {
    std::fprintf(stderr, "asset_gen: cannot write %s\n", path.c_str());
    return false;
  }
  file << content;
  return static_cast<bool>(file);
}

bool writeToneWav(const std::string& path) {
  kimia::AudioBuffer buffer;
  buffer.channels = 2;
  buffer.sampleRate = 44100;
  buffer.frameCount = 22050U;  // 0.5 s
  buffer.samples.resize(static_cast<usize>(buffer.frameCount) * 2U);
  const f64 twoPi = 6.28318530717958647692;
  for (u64 frame = 0; frame < buffer.frameCount; ++frame) {
    const f64 t = static_cast<f64>(frame) / static_cast<f64>(buffer.sampleRate);
    const f64 value = 0.4 * std::sin(twoPi * 440.0 * t);
    const usize base = static_cast<usize>(frame) * 2U;
    buffer.samples[base] = static_cast<f32>(value);
    buffer.samples[base + 1U] = static_cast<f32>(value);
  }
  if (!buffer.writeWAV(path)) {
    std::fprintf(stderr, "asset_gen: cannot write %s\n", path.c_str());
    return false;
  }
  return true;
}

bool writeTestPng(const std::string& path) {
  const i32 width = 6;
  const i32 height = 3;
  const i32 channels = 3;
  const i32 colors[6][3] = {
      {255, 0, 0},   // red
      {255, 165, 0}, // orange
      {255, 255, 0}, // yellow
      {0, 128, 0},   // green
      {0, 0, 255},   // blue
      {128, 0, 128}, // purple
  };
  const f64 rowScale[3] = {1.0, 0.75, 0.5};
  kimia::Image image;
  image.width = width;
  image.height = height;
  image.channels = channels;
  image.pixels.resize(static_cast<usize>(width) * static_cast<usize>(height) * static_cast<usize>(channels));
  for (i32 y = 0; y < height; ++y) {
    for (i32 x = 0; x < width; ++x) {
      u8* pixel = image.at(x, y);
      for (i32 c = 0; c < channels; ++c) {
        pixel[c] = static_cast<u8>(std::lround(static_cast<f64>(colors[x][c]) * rowScale[y]));
      }
    }
  }
  if (!image.writePNG(path)) {
    std::fprintf(stderr, "asset_gen: cannot write %s\n", path.c_str());
    return false;
  }
  return true;
}

bool writeTestJpg(const std::string& path) {
  const i32 width = 2;
  const i32 height = 2;
  const i32 channels = 3;
  const u8 pixels[12] = {
      255, 255, 255, 0, 0, 0,  //
      255, 0, 0, 0, 255, 0,    //
  };
  kimia::Image image;
  image.width = width;
  image.height = height;
  image.channels = channels;
  image.pixels.assign(pixels, pixels + 12U);
  if (!image.writeJPG(path, 95)) {
    std::fprintf(stderr, "asset_gen: cannot write %s\n", path.c_str());
    return false;
  }
  return true;
}

const char* kCubeObj =
    "# generated by kimia_asset_gen\n"
    "o Cube\n"
    "v -0.5 -0.5 -0.5\n"
    "v 0.5 -0.5 -0.5\n"
    "v 0.5 0.5 -0.5\n"
    "v -0.5 0.5 -0.5\n"
    "v -0.5 -0.5 0.5\n"
    "v 0.5 -0.5 0.5\n"
    "v 0.5 0.5 0.5\n"
    "v -0.5 0.5 0.5\n"
    "vn 0 0 -1\n"
    "vn 0 0 1\n"
    "vn -1 0 0\n"
    "vn 1 0 0\n"
    "vn 0 -1 0\n"
    "vn 0 1 0\n"
    "vt 0 0\n"
    "vt 1 0\n"
    "vt 1 1\n"
    "vt 0 1\n"
    "f 1/1/1 4/4/1 3/3/1 2/2/1\n"
    "f 6/1/2 7/2/2 8/3/2 5/4/2\n"
    "f 5/1/3 8/2/3 4/3/3 1/4/3\n"
    "f 2/1/4 3/2/4 7/3/4 6/4/4\n"
    "f 5/1/5 1/4/5 2/2/5 6/3/5\n"
    "f 4/1/6 8/2/6 7/3/6 3/4/6\n";

const char* kQuadObj =
    "# generated by kimia_asset_gen\n"
    "o Quad\n"
    "v 0 0 0\n"
    "v 1 0 0\n"
    "v 1 1 0\n"
    "v 0 1 0\n"
    "vn 0 0 1\n"
    "vt 0 0\n"
    "vt 1 0\n"
    "vt 1 1\n"
    "vt 0 1\n"
    "f 1/1/1 2/2/1 3/3/1\n"
    "f 1/1/1 3/3/1 4/4/1\n";

}  // namespace

int main() {
  const std::string dir = assetDir();
  bool ok = true;
  ok = writeToneWav(dir + "/tone.wav") && ok;
  ok = writeTestPng(dir + "/2x3.png") && ok;
  ok = writeTestJpg(dir + "/2x2.jpg") && ok;
  ok = writeText(dir + "/cube.obj", kCubeObj) && ok;
  ok = writeText(dir + "/quad.obj", kQuadObj) && ok;
  if (!ok) return 1;
  std::printf("asset_gen: test assets written to %s\n", dir.c_str());
  return 0;
}
