#!/usr/bin/env python3
"""Pack a set of directory trees into a self-contained C++ translation unit.

Usage:
    make_embedded_assets.py <out.cpp> <srcDir>=<destDir> [<srcDir>=<destDir> ...]

Every file under each <srcDir> is embedded as raw bytes and exposed through
kimia::embedded::assetList() with its path relative to <destDir>. The engine
unpacks them at runtime so a single .exe / .apk runs with nothing next to it.

Bytes are emitted as concatenated `\\xNN` string literals in <=16 KB chunks.
This matters: MSVC rejects a single string literal longer than 16,380
single-byte characters (error C2026), while GCC and Clang parse larger ones.
Chunked string literals compile everywhere, so the Windows self-contained exe
and the APK share one generator.
"""
import os
import sys

# MSVC per-literal limit is 16,380 single-byte chars (C2026); stay below it.
CHUNK = 16000  # bytes per string literal; each byte -> 4 source chars ("\xNN")


def main():
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__)
        return 2

    out_cpp = sys.argv[1]
    mappings = sys.argv[2:]

    entries = []  # (path_in_binary, raw_bytes)
    for mapping in mappings:
        if "=" not in mapping:
            sys.stderr.write("bad mapping (expected src=dest): %s\n" % mapping)
            return 2
        src, dest = mapping.split("=", 1)
        if not os.path.isdir(src):
            sys.stderr.write("skip missing dir: %s\n" % src)
            continue
        for dirpath, dirnames, filenames in os.walk(src):
            dirnames.sort()
            for filename in sorted(filenames):
                full = os.path.join(dirpath, filename)
                rel = os.path.relpath(full, src).replace("\\", "/")
                with open(full, "rb") as f:
                    data = f.read()
                entries.append((dest.rstrip("/") + "/" + rel, data))

    entries.sort(key=lambda e: e[0])

    with open(out_cpp, "w", encoding="utf-8") as f:
        f.write("// Generated by Tools/make_embedded_assets.py — do not edit.\n")
        f.write("#include <kimia/EmbeddedAssets.h>\n\n")
        f.write("namespace kimia { namespace embedded {\n\n")
        f.write("// Concatenated \\xNN literals: MSVC caps one literal at 16,380 single-byte\n")
        f.write("// characters (C2026), so each chunk stays well below that. Every byte is\n")
        f.write("// escaped, so no raw quote, backslash or newline ever reaches the parser.\n")
        f.write("static const char kBlob[] =\n")
        blob = bytearray()
        for _, data in entries:
            blob += data
        if blob:
            for i in range(0, len(blob), CHUNK):
                chunk = blob[i:i + CHUNK]
                f.write('    "')
                for b in chunk:
                    f.write("\\x%02x" % b)
                f.write('"\n')
        else:
            f.write('    ""\n')
        f.write("    ;\n\n")
        f.write("static const Asset kAssets[] = {\n")
        offset = 0
        for path, data in entries:
            f.write('    {"%s", reinterpret_cast<const unsigned char*>(kBlob) + %d, %d},\n'
                    % (path, offset, len(data)))
            offset += len(data)
        f.write("    {nullptr, nullptr, 0},\n")
        f.write("};\n\n")
        f.write("const Asset* assetList() { return kAssets; }\n\n")
        f.write("} }  // namespace kimia::embedded\n")

    total = sum(len(d) for _, d in entries)
    print("embedded %d files, %d bytes -> %s" % (len(entries), total, out_cpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
